In [95]:
import itertools
import logging
from tqdm import tqdm

from datamaestro import prepare_dataset
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import torch.nn as nn
import torch.optim as optim
from torch.utils.tensorboard import SummaryWriter
import torch
import torch.nn.functional as F
from typing import List
import time
logging.basicConfig(level=logging.INFO)

ds = prepare_dataset('org.universaldependencies.french.gsd')


# Format de sortie décrit dans
# https://pypi.org/project/conllu/

class Vocabulary:
    """Permet de gérer un vocabulaire.

    En test, il est possible qu'un mot ne soit pas dans le
    vocabulaire : dans ce cas le token "__OOV__" est utilisé.
    Attention : il faut tenir compte de cela lors de l'apprentissage !

    Utilisation:

    - en train, utiliser v.get("blah", adding=True) pour que le mot soit ajouté
      automatiquement
    - en test, utiliser v["blah"] pour récupérer l'ID du mot (ou l'ID de OOV)
    """
    OOVID = 1
    PAD = 0

    def __init__(self, oov: bool):
        self.oov =  oov
        self.id2word = [ "PAD"]
        self.word2id = { "PAD" : Vocabulary.PAD}
        if oov:
            self.word2id["__OOV__"] = Vocabulary.OOVID
            self.id2word.append("__OOV__")

    def __getitem__(self, word: str):
        if self.oov:
            return self.word2id.get(word, Vocabulary.OOVID)
        return self.word2id[word]

    def get(self, word: str, adding=True):
        try:
            return self.word2id[word]
        except KeyError:
            if adding:
                wordid = len(self.id2word)
                self.word2id[word] = wordid
                self.id2word.append(word)
                return wordid
            if self.oov:
                return Vocabulary.OOVID
            raise

    def __len__(self):
        return len(self.id2word)

    def getword(self,idx: int):
        if idx < len(self):
            return self.id2word[idx]
        return None

    def getwords(self,idx: List[int]):
        return [self.getword(i) for i in idx]



class TaggingDataset():
    def __init__(self, data, words: Vocabulary, tags: Vocabulary, adding=True):
        self.sentences = []

        for s in data:
            self.sentences.append(([words.get(token["form"], adding) for token in s], [tags.get(token["upostag"], adding) for token in s]))
    def __len__(self):
        return len(self.sentences)
    def __getitem__(self, ix):
        return self.sentences[ix]


def collate(batch):
    """Collate using pad_sequence"""
    return tuple(pad_sequence([torch.LongTensor(b[j]) for b in batch]) for j in range(2))


logging.info("Loading datasets...")
words = Vocabulary(True)
tags = Vocabulary(False)
train_data = TaggingDataset(ds.train, words, tags, True)
dev_data = TaggingDataset(ds.validation, words, tags, True)
test_data = TaggingDataset(ds.test, words, tags, False)


logging.info("Vocabulary size: %d", len(words))


BATCH_SIZE=100

train_loader = DataLoader(train_data, collate_fn=collate, batch_size=BATCH_SIZE, shuffle=True)
dev_loader = DataLoader(dev_data, collate_fn=collate, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_data, collate_fn=collate, batch_size=BATCH_SIZE)

INFO:root:Loading datasets...
INFO:root:Vocabulary size: 42930


In [127]:
class LSTMTag(nn.Module):
    def __init__(self, embedding_dim, hidden_dim, vocab_size, target_size):
        super(LSTMTag, self).__init__()
        
        self.hidden_dim = hidden_dim
        self.word_embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim)
        self.hidden2tag = nn.Linear(hidden_dim, target_size)
        
    def forward(self, sentence):
        
        embeds = self.word_embeddings(sentence)
        lstm_out, (hidden_state, cell_state) = self.lstm(embeds)
        tag_space = self.hidden2tag(lstm_out)
        return tag_space

In [128]:
len(tags)

19

In [134]:
EMBEDDING_DIM = 60
HIDDEN_DIM = 120


model = LSTMTag(EMBEDDING_DIM, HIDDEN_DIM, len(words), len(tags))
criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = optim.Adam(model.parameters(), lr=0.1)



for epoch in range(50):
    for sentence, tag in train_loader:
        target = tag.permute(1,0)
        model.zero_grad()
        tag_scores = model(sentence).permute(1,2,0)
        #import ipdb;ipdb.set_trace()
        loss = criterion(tag_scores, target)
        loss.backward()
        optimizer.step()
    print(f"epoch {epoch} : Loss {loss}")


epoch 0 : Loss 2.9518022537231445
epoch 0 : Loss 2.8045825958251953
epoch 0 : Loss 3.4375267028808594
epoch 0 : Loss 2.165649175643921
epoch 0 : Loss 1.6507859230041504
epoch 0 : Loss 1.412873387336731
epoch 0 : Loss 1.191569447517395
epoch 0 : Loss 0.9852752685546875
epoch 0 : Loss 0.9779251217842102
epoch 0 : Loss 0.8854538202285767
epoch 0 : Loss 0.9006351232528687
epoch 0 : Loss 0.834964394569397
epoch 0 : Loss 0.7934458255767822
epoch 0 : Loss 0.7474129796028137
epoch 0 : Loss 0.7518255710601807
epoch 0 : Loss 0.7360935807228088
epoch 0 : Loss 0.6953868269920349
epoch 0 : Loss 0.6793655753135681
epoch 0 : Loss 0.6263436675071716
epoch 0 : Loss 0.6632508039474487
epoch 0 : Loss 0.6042245626449585
epoch 0 : Loss 0.5866310596466064
epoch 0 : Loss 0.5810867547988892
epoch 0 : Loss 0.5633209347724915
epoch 0 : Loss 0.5712041258811951
epoch 0 : Loss 0.6019901633262634
epoch 0 : Loss 0.5561022162437439
epoch 0 : Loss 0.5132210850715637
epoch 0 : Loss 0.47939828038215637
epoch 0 : Loss 0.

KeyboardInterrupt: 

In [ ]:
print("Training Finished!!!\nAgain testing on unknown data")
with torch.no_grad():
    for seq in [seq1, seq2]:
        inputs = prepare_sequence(seq, word_to_ix)
        tag_scores = model(inputs)
        _, indices = torch.max(tag_scores, 1)
        ret = []
        for i in range(len(indices)):
            for key, value in tag_to_ix.items():
                if indices[i] == value:
                    ret.append((seq[i], key))
        print(ret)

In [28]:
train_data.__getitem__(1)

([21, 22, 23, 24, 9, 18, 25, 26, 27, 14, 28, 29, 9, 30, 31, 27, 32, 20],
 [1, 2, 4, 5, 7, 1, 2, 11, 7, 1, 2, 10, 7, 1, 2, 7, 12, 10])

In [33]:
tags.getword(train_data.__getitem__(0)[1][1])

'œuvre'

In [100]:
for sentence, tag in train_loader:
    a = tag
    break

In [117]:
F.one_hot(a[:,0],19).shape

torch.Size([58, 19])

In [121]:
F.one_hot(a,19)[:,0][0]

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
F.one_hot(a[:,0],19)[0]

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [107]:
a[:,0]

tensor([ 6,  7,  9,  5,  6,  7,  1,  2, 10,  1,  2, 11,  7,  1,  2, 16, 16, 10,
        12, 12, 13, 12, 12, 12, 10,  5,  1,  2, 10,  5,  7,  2,  7, 12, 12, 10,
         2,  7, 12, 12, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])